{"componentChunkName":"component---src-templates-blog-js","path":"/2019/01/17/nvidia-libnvidia-fatbinaryloader/","result":{"data":{"blog":{"id":"e4c35056-400e-5cf1-b25d-b3ec15188a7b","html":"<p>最近搞装机的事情很是烦躁，非常理解做运维的同学的辛苦了。尤其是当出现一些不知所云的错误的时候，真的是头都炸了。而且如果不能保持冷静还可能把原先做的工作因为一两个失误毁于一旦。</p>\n<p>从现在开始尝试频繁的记录在运维的过程中遇到的各种各样的错误。这次是记录 dgx1 上 <code>nvidia-docker2</code> 异常，导致 <code>nvidia-device-plugin</code> 无法启动。</p>\n<p>将 <code>dgx1</code> 加入 <code>kubernetes</code> 集群之后发现其 <code>nvidia-device-plugin</code> 启动报错 <code>RunContainerError</code>，<code>k describe pod</code> 发现错误信息：</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">Error: failed to start container \"nvidia-device-plugin-ctr\": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"process_linux.go:385: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --utility --pid=11077 /var/lib/docker/overlay2/510a6de5ed82decf7421a392e5274b4fe47e8d0cd3610175c3550f1d26c91376/merged]\\\\\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\\\\\n\\\\\\\"\\\"\": unknown</code></pre></div>\n<p>说是驱动有问题，第一个想到的就是因为将早先的 <code>nvidia-384</code> 驱动更新到了 <code>nvidia-410</code> 可能有问题，再重启之后没有作用，于是尝试通过 <code>apt</code> 重新安装 <code>nvidia-410</code>：</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">$ add-apt-repository ppa:graphics-drivers/ppa\n$ apt update\n$ apt install nvidia-410</code></pre></div>\n<p>重启后依然发现类似问题，再去搜索发现 <a href=\"https://zhuanlan.zhihu.com/p/37519492\">https://zhuanlan.zhihu.com/p/37519492</a> 和我遇到的问题类似，通过命令 <code>nvidia-container-cli -k -d /dev/tty info</code> 得到具体的报错：</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">E0117 08:51:20.843706 12905 driver.c:197] could not start driver service: load library failed: libnvidia-fatbinaryloader.so.384.145: cannot open shared object file: no such file or directory</code></pre></div>\n<p><code>384</code> 这个驱动版本我明明已经删了，为什么还要找这个库呢？是不是因为新的 <code>410</code> 安装的不全呢？再往后看，提到</p>\n<blockquote>\n<p>安装驱动的时候会自动安装这个 libcuda1-384 包的，估计是什么历史遗留问题，或者是 purge 又 install 把包的依赖关系搞坏了，因此现在需要重新安装。</p>\n</blockquote>\n<p>立即想到我的 <code>410</code> 是不是也没有安装 <code>libcuda1-410</code> 呢？赶紧 <code>apt search libcuda</code> 发现果然有这么个依赖，<code>apt install libcuda1-410</code> 赶紧安装，再次跑 <code>nvidia-container-cli -k -d /dev/tty info</code> 就一切正常了。</p>","tableOfContents":"","frontmatter":{"title":"记一次 nvidia docker 错误追查","date":"January 17, 2019","tags":["docker","devops","kubernetes","gpu","nvidia"]},"excerpt":"最近搞装机的事情很是烦躁，非常理解做运维的同学的辛苦了。尤其是当出现一些不知所云的错误的时候，真的…"}},"pageContext":{"id":"e4c35056-400e-5cf1-b25d-b3ec15188a7b"}},"staticQueryHashes":["4202924991"]}